/*
 * Fate_Frame.java
 *
 * Created on __DATE__, __TIME__
 */

package jiemian;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;

import javax.jws.WebParam.Mode;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import database.ModelFactory;
import database.Player_data;

/**
 *
 * @author  __USER__
 */
public class Fate_Frame extends javax.swing.JFrame {
	private int i = 0;
	private Player_data player;

	/** Creates new form Fate_Frame */
	public Fate_Frame(Player_data player) {
		this.player = player;
		initComponents();
		ModelFactory.playBackmusic(2);
		this.setLocationRelativeTo(null);
	}

	public Fate_Frame() {
		initComponents();
		ModelFactory.playBackmusic(2);
		this.setLocationRelativeTo(null);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		imageJpanel1 = new jiemian.ImageJpanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setIconImage(new ImageIcon("./src/img/8.gif").getImage());
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				closemusic(evt);
			}
		});

		imageJpanel1.setImage(new ImageIcon("./src/img/Fate01.png").getImage());
		imageJpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				Change(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 18));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2
				.setText("         \u6c89\u7761\u4e2d\u7684\u8857\u9053\u6bd4\u5e73\u5e38\u66f4\u52a0\u5bc2\u9759\u3002\u5927\u6982\u662f\u5bb3\u6015\u9891\u7e41\u53d1\u751f\u7684\u602a\u5f02\u4e8b\u4ef6\u5427");
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				Change(evt);
			}
		});

		jProgressBar1.setForeground(new java.awt.Color(204, 204, 0));

		jLabel3.setFont(new java.awt.Font("张海山锐线体简", 1, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u5b8c\u6210\u5ea6\uff1a");

		javax.swing.GroupLayout imageJpanel1Layout = new javax.swing.GroupLayout(
				imageJpanel1);
		imageJpanel1.setLayout(imageJpanel1Layout);
		imageJpanel1Layout
				.setHorizontalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jProgressBar1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				185,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				842,
																				Short.MAX_VALUE))
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				45,
																				45,
																				45)
																		.addGroup(
																				imageJpanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								1081,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								113,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));
		imageJpanel1Layout
				.setVerticalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								imageJpanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																jProgressBar1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(474, 474, 474)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												18,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(33, 33, 33)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void closemusic(java.awt.event.WindowEvent evt) {
		ModelFactory.stopBackmusic();
	}

	private void Change(java.awt.event.MouseEvent evt) {

		try {
			this.jProgressBar1.setMinimum(1);
			this.jProgressBar1.setMaximum(93);
			i++;
			if (i <= 2 && i >= 1) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate02.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 4 && i >= 2) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate03.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 9 && i >= 5) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate04.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 11 && i >= 10) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate05.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 30 && i >= 12) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate06.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i == 31) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
				ModelFactory.stopBackmusic();
				new Baoju1().setVisible(true);

				//i = ModelFactory.getProgress("圣杯战争", player.getName());

			}
			if (i <= 41 && i >= 32) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate07.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i == 42) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate07.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
				ModelFactory.stopBackmusic();
				new Baoju2().setVisible(true);

				//i = ModelFactory.getProgress("圣杯战争", player.getName());

			}
			if (i == 43) {
				ModelFactory.playBackmusic(2);
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));

				imageJpanel1.setImage(new ImageIcon("./src/img/fate07.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 66 && i >= 44) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));

				imageJpanel1.setImage(new ImageIcon("./src/img/fate07.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i <= 92 && i >= 67) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate08.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
			}
			if (i == 93) {
				jLabel1.setText(ModelFactory.getDialogueName(i));
				jLabel2.setText(ModelFactory.getDialogue(i));
				imageJpanel1.setImage(new ImageIcon("./src/img/fate08.png")
						.getImage());
				jProgressBar1.setValue(i);
				if (i > ModelFactory.getProgress("圣杯战争", player.getName())) {
					ModelFactory.sendProgress(i, "圣杯战争", player.getName());
				}
				JOptionPane.showMessageDialog(this, "恭喜您完成了fate剧情");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Fate_Frame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private jiemian.ImageJpanel imageJpanel1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JProgressBar jProgressBar1;
	// End of variables declaration//GEN-END:variables

}